### ISSUE TITLE
I&C issue: Open in Search

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1113]
https://impresso-project.ch/app/compare?left=CiYQAhgHIAEqBmFybmhlbSoFYW1oZW0qB2FybmhlaW0qBmFybmVobQoEEAEYAgpOCAEQAhgSKhZ0bS1mci1hbGwtdjIuMF90cDUyX2ZyKhZ0bS1kZS1hbGwtdjIuMF90cDg0X2RlKhZ0bS1mci1hbGwtdjIuMF90cDIwX2ZyCgwIARABGAcgASoCbGUKCBABGAwqAmZy

Steps:

1. run searches in A and B
2. click open results in common in Search
3. use browser back button OR click on I&C again
4. search query from B is added to A

![image](https://user-images.githubusercontent.com/4408050/170814069-8e57b0e2-6388-477c-a42c-d3d6922578d0.png)

**Comment by danieleguido** [comment]
The expected behaviour is: 

1. run searches in A and B
2. click open results in common in Search
3. **use browser back button** (do not click on I&C, there's no memory of A & B queries)
4. search query A and B are like they were before

However, in the current implementation, the link to the search page (aka _open results in common_ button) makes use of the old parameter `f` and not `sq` (serialized search query). 
Behind the scenes, f get transformed into `sq` but this get troubles in history, this is to be checked ;)

**Comment by danieleguido** [comment]
Now `sq` is correctly forwarded, deployed in current develop.
