### ISSUE TITLE
TR at Scale: remaining bugs

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1170]
- [x] changel label in mouseovers
range -> cluster size: 30-40 // even better: 30-40 clusters
value -> lexical overlap: 30-40% // even better: 30-40% lexical overlap
range -> days: 10.000 - 11.000  // even better: 10.000 - 11.000 days
<img width="399" alt="grafik" src="https://github.com/impresso/impresso-frontend/assets/4408050/726bc214-90fd-4e69-95c3-7b01d5a32dc2">

- [x] fix newspaper filter facet
- [x] Passages view: group passages by cluster
- [ ] - [ ] rename passage size to "length"

<img width="380" alt="grafik" src="https://github.com/impresso/impresso-frontend/assets/4408050/7f2abd8d-d552-46f0-a2cc-c1285cb26409">

**Comment by danieleguido** [comment]
Cluster view, with custom search query: https://impresso-project.ch/app/text-reuse/clusters?p=1&sq=ChIQAhgHIAEqClJlbWVyc2NoZW4KAhgCCiAQAhgHIAEqCW51Y2xlYWlyZSoNYXRvbWtyYWZ0d2Vyaw%3D%3D

**Comment by piconti** [comment]
Adding to this issue instead of opening new ones which will be closely related. 
When browsing in the text-reuse tab and ordining by other things than date, an error (code 500) shows up:
![Screenshot 2024-05-02 at 15 30 17](https://github.com/impresso/impresso-frontend/assets/43445043/ddaaecc9-a9f9-4642-b3f7-56cde3cd0952)

https://impresso-project.ch/app/text-reuse/clusters?p=1&sq=&sort=clusterSize
Adding both screenshot and link because the link shows only 1 cluster as I had applied no filtering and was browsing all 6 million clusters.

**Comment by danieleguido** [comment]
@piconti this is related to IML it seems, https://github.com/impresso/impresso-middle-layer/issues/385

**Comment by danieleguido** [comment]
fixed in dev
