### ISSUE TITLE
Bug in collections filter: article / results 

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1210]
1) article count is off:  38,000,052 articles (380,052 results) 

2) once filter for a collection is applied article count looks strange: (empty) (380,052 results)

3) for better understanding how about rephrasing: "1000 articles, 33 match current query"

**Comment by danieleguido** [comment]
There is a difference between the selected items in filters and the buckets, we have this

<img width="391" alt="Screenshot 2024-09-30 at 09 12 58" src="https://github.com/user-attachments/assets/c20bcbee-5351-4b42-90fa-2518f31adf6d">

instead of:
<img width="386" alt="Screenshot 2024-09-30 at 09 13 33" src="https://github.com/user-attachments/assets/b79173b9-4078-4200-b38b-124a743f1d0e">

This bug is related to the filterItems service from IML:

<img width="617" alt="Screenshot 2024-09-30 at 09 15 18" src="https://github.com/user-attachments/assets/0e1251db-7778-4e08-b388-d7e6e2800268">
