### ISSUE TITLE
The yellow navigator is irritating in text view mode

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#122]
The yellow region marker on the thumbnail that shows the viewed image in the image mode is irritating when the user is in text mode (and in text mode the viewer should also jump to the start of the article)

E.g. https://impresso-project.ch/dev/#/issue/GDL-1902-05-12-a/page/GDL-1902-05-12-a-p0002/article/GDL-1902-05-12-a-i0013

![image](https://user-images.githubusercontent.com/3041168/49937172-3b879d80-fed6-11e8-8100-c2359cb0a054.png)

In image mode, everything makes sense, and the article is recognized via its blue region:

![image](https://user-images.githubusercontent.com/3041168/49937293-93be9f80-fed6-11e8-950e-7fa5b376fae6.png)

**Comment by tvanbeek** [comment]
fixed in pull request [123](https://github.com/impresso/impresso-frontend/pull/123)

**Comment by danieleguido** [comment]
Thanks @simon-clematide
The yellow area is related to the facsimile viewer and represents the zoom level; it is merely a "leftover" since you can switch modality and go back to the exact position you left.
Ideally we should highlight the region in blue the thumbnail, so that it remains coherent. What do you think?
an easy fix: hide the yellow area.

**Comment by simon-clematide** [comment]
Yes, coherency in terms of yellow marks visible regions, blue marks content items in focus seems to be the most natural thing.  As it is in the search result:
![image](https://user-images.githubusercontent.com/3041168/49952816-0a6e9380-fefd-11e8-80da-3ac5ddf6f070.png)

**Comment by simon-clematide** [comment]
Well, I read something, but cannot pull;-)
