### ISSUE TITLE
Number of hits is irritating when interface is slow

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#1252]
Yesterday, when reaction of the interface was slow, it maximally irritated the participants that the interface showed so many hits for the query "swiss national library." It also made me believe that we are searching in other fields than text fields. 
When a query updates the query formulation but leaves the number of hits to the old number, it is very confusing. 

Suggested fix: Just reset the hit number when launching a query, don't leave the old numbers there together with a fresh query.

![image](https://github.com/user-attachments/assets/b5917529-acba-45d3-a433-271bc9b580eb)

**Comment by danieleguido** [comment]
Fixed in our develop branch, I've added "loading..." combined with opacity, I hope it helps. The whole interface is now blazing fast ;)
Probably we should reconsider wording?

<img width="955" alt="Screenshot 2024-09-27 at 09 25 10" src="https://github.com/user-attachments/assets/a439b03a-975f-4068-9fdb-d772974f2e82">

**Comment by simon-clematide** [comment]
@danieleguido  Very nice. Regarding wording:
 Maybe ...searching ?
