### ISSUE TITLE
manually typing in date ranges in Search does not work

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#825]
Failed to change dates to 1845-01-01 / 1845-12-31 both with and without a previously set date range filter

https://dev.impresso-project.ch/app/search?f=%5B%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221897-05-22T00%3A00%3A00Z%20TO%201845-12-31T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by mduering** [comment]
perhaps related? manual editing of the search pill does not work: https://dev.impresso-project.ch/app/search?f=%5B%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221844-05-22T00%3A00%3A00Z%20TO%201833-12-31T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by danieleguido** [comment]
Cannot reproduce, it works for me! It is related to the fact the the "last date" is previous to the "first date" (1844 to 1833) ?

**Comment by theorm** [comment]
I just reproduced it and I can see the reason why it does not update the dates: the page reads filters from the old URL parameter `f` but updates the new one `sq`. The changes are stored in the url but never read. I don't think this is the original cause of the problem though because Marten reported it a month ago when the new URL parameter was not used on the Search page.

**Comment by theorm** [comment]
@mduering , can you please test it again when you have time? It now may have been fixed.

**Comment by mduering** [comment]
works fine, thanks!
