### ISSUE TITLE
compare page > loading blocks all user interaction

### ISSUE THREAD

**Issue by PaulSchroeder** [impresso/impresso-frontend#857]
we should avoid using loading modal, as it blocks all user interaction, even navigation.
consider using less intrusive method.

<img width="624" alt="Screenshot 2020-05-05 at 11 35 53" src="https://user-images.githubusercontent.com/32929425/81053103-dcf50200-8ec4-11ea-8b1e-2f60a0670388.png">

Since we moved to bootstrap 4, we have access to the new spinners. Perhaps we should swap the spinners with bootstrap "native" ones ? 
https://getbootstrap.com/docs/4.4/components/spinners/

**Comment by danieleguido** [comment]
We can use new spinners of course :), but our main concern was server overload (especially mysql): the only solution is to cancel requests when user abandons the page or click elsewhere on the page. That's why we decided to block all interactions during loading, but this can be a good issue for the next release.

**Comment by theorm** [comment]
I agree that we need to replace this blocking spinner. I'm sure we can relieve the load on MySQL by caching more aggressively. I'd work on it straight after the upcoming release.

**Comment by PaulSchroeder** [comment]
yea it would be cool to solve it with caching for the upcoming release.

meanwhile, it’s a good idea to add a “cancel request” to the modal.
