### ISSUE TITLE
adjusted dates in search pill are ignored

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#957]
https://impresso-project.ch/app/search?sq=CggQAhgWKgJMVQoCGAIKDhACGAcgASoGbWVyemlnCjIQAhgKKiwxOTM2LTEyLTE3VDAwOjAwOjAwWiBUTyAxOTQ0LTA4LTIwVDIzOjU5OjU5Wg%3D%3D&p=1

1. selected dates in timeline 
2. ran query
3. adjusted in search pill, reran query

**Comment by theorm** [comment]
I could not reproduce (I got an error which I know was fixed in dev)  but I suspect if this problem is different to the error issue then it is most likely fixed in dev https://dev.impresso-project.ch/app/search?sq=CggQAhgWKgJMVQoCGAIKDhACGAcgASoGbWVyemlnCjIQAhgKKiwxOTM2LTEyLTE2VDAwOjAwOjAwWiBUTyAxOTQ0LTA4LTIwVDIzOjU5OjU5Wg%3D%3D&p=1

**Comment by danieleguido** [comment]
fixed in current dev version
