### ISSUE TITLE
Search page: facets properties are not loaded when there is no result

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#969]
example query: https://dev.impresso-project.ch/app/search?sq=Cg0QAhgDIAEqBWZyaXR6Ck4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwMDdfZnIqFnRtLWZyLWFsbC12Mi4wX3RwNjZfZnIqFnRtLWZyLWFsbC12Mi4wX3RwNjNfZnIKAhgCCmEQAhgJKiBhaWRhLTAwMDEtNTAtTGVzX1BvbnRzLWRlLU1hcnRlbCoVYWlkYS0wMDAxLTU0LUxhdXNhbm5lKhZ0bS1mci1hbGwtdjIuMF90cDIyX2ZyKgphcm1ldGV1ZmVs&p=1

**Comment by theorm** [comment]
Turned out the query is broken. The `newspaper` filter contains a mix of entity, topic and newspaper IDs. It will be helpful to know how this query has been created. If through the interface, there is certainly a bug somewhere allowing it to be created.
Closing this until we have more information.

 <img width="438" alt="Screen Shot 2020-08-27 at 16 10 46" src="https://user-images.githubusercontent.com/89853/91453723-679cab00-e880-11ea-930d-3fb147b8117c.png">
