### ISSUE TITLE
DE topic on FR article

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#978]
I came across this article, written in French, with German topics...
https://dev.impresso-project.ch/app/issue/luxwort-1933-10-24-a/page/luxwort-1933-10-24-a-p0008/article/luxwort-1933-10-24-a-i0032

**Comment by simon-clematide** [comment]
The current language information still trusts too much to the original language labels from the archives. As I improved language identification (LID) by training an own model that is not so easily confused by German texts mentioning Luxembourgish names, I will trust the automatic LID more. This should then exclude cases like this because LID will recognize French and we will trust the LID more than the original language tag.

**Comment by danieleguido** [comment]
Hi @Bunoute, @simon-clematide can we move this conversation to another channel ? Probably to our repo on [impresso-text-acquisition](https://github.com/impresso/impresso-text-acquisition) ? 
Closing for now as it is not bug on the frontend app :)
